/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javase.oop.gui;

import java.util.ArrayList;
import javase.oop.orders.Order;
import javase.oop.orders.OrderItem;
import javase.oop.products.Product;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class jInternalFrameCart extends javax.swing.JInternalFrame {

        private static jInternalFrameCart myInstance;
    /**
     * Creates new form jInternalFrameCart
     */
    public jInternalFrameCart() {
        initComponents();
    }

    public static jInternalFrameCart getMyInstance() {
            if(myInstance == null){ // first refernce
                myInstance = new jInternalFrameCart();
            }
        
        return myInstance;
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPreviewCart = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCart = new javax.swing.JTable();
        jLabelOrderTotal = new javax.swing.JLabel();
        jTextFieldOrderTotal = new javax.swing.JTextField();
        jButtonRemoveItemCart = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cart Preview");

        jLabelPreviewCart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPreviewCart.setText("Preview Your Cart");

        jTableCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Line Nbr", "Product Name", "Unit Price", "Quantity", "Item Total", "Product Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableCart);

        jLabelOrderTotal.setText("Order Total");

        jButtonRemoveItemCart.setText("Remove Item");
        jButtonRemoveItemCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveItemCartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addComponent(jLabelOrderTotal)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldOrderTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabelPreviewCart, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jButtonRemoveItemCart, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelPreviewCart, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRemoveItemCart, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOrderTotal)
                    .addComponent(jTextFieldOrderTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemoveItemCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveItemCartActionPerformed

        Product product = (Product) jTableCart.getValueAt( jTableCart.getSelectedRow() , 5);

        Order currentOrder = jInternalFrameLogin.getCurrentOrder();
        currentOrder.deleteOrderItem(product);

        reFillCart(currentOrder);
    }//GEN-LAST:event_jButtonRemoveItemCartActionPerformed

    public void reFillCart(Order currentOrder){
              ArrayList<OrderItem> itemsList = currentOrder.getItemsList();
             DefaultTableModel tm =  (DefaultTableModel) jTableCart.getModel();
                    tm.setRowCount(0);
                    
        for(OrderItem item : itemsList){

               Object[] rowData = { item.getLinNbr(), item.getProduct().getName(),
                            item.getUnitPrice(), item.getQuantity(), item.getItemTotal(),
                                    item.getProduct()
                                    };
               
               tm.addRow(rowData);   
              }
              
             jTextFieldOrderTotal.setText( String.valueOf( currentOrder.getOrderTotal() )   );
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRemoveItemCart;
    private javax.swing.JLabel jLabelOrderTotal;
    private javax.swing.JLabel jLabelPreviewCart;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCart;
    private javax.swing.JTextField jTextFieldOrderTotal;
    // End of variables declaration//GEN-END:variables
}
