/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javase.oop.gui;

import javase.oop.orders.Order;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class MasterForm extends javax.swing.JFrame {
   
    /**
     * Creates new form MasterForm
     */
    public MasterForm() {
        initComponents();
        // Master Form set centered
       this.setLocationRelativeTo(null);
       this.setExtendedState(JFrame.MAXIMIZED_BOTH);
       
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneMaster = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUserActions = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuItemExitApplication = new javax.swing.JMenuItem();
        jMenuProductsSetup = new javax.swing.JMenu();
        jMenuItemSoftware = new javax.swing.JMenuItem();
        jMenuItemHardware = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPaneMasterLayout = new javax.swing.GroupLayout(jDesktopPaneMaster);
        jDesktopPaneMaster.setLayout(jDesktopPaneMasterLayout);
        jDesktopPaneMasterLayout.setHorizontalGroup(
            jDesktopPaneMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        jDesktopPaneMasterLayout.setVerticalGroup(
            jDesktopPaneMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        jMenuUserActions.setText("User Actions");
        jMenuUserActions.setEnabled(false);

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuUserActions.add(jMenuItemLogout);

        jMenuItemExitApplication.setText("Exit Application");
        jMenuItemExitApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitApplicationActionPerformed(evt);
            }
        });
        jMenuUserActions.add(jMenuItemExitApplication);

        jMenuBar1.add(jMenuUserActions);

        jMenuProductsSetup.setText("Products Setup");
        jMenuProductsSetup.setEnabled(false);

        jMenuItemSoftware.setText("Software");
        jMenuItemSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSoftwareActionPerformed(evt);
            }
        });
        jMenuProductsSetup.add(jMenuItemSoftware);

        jMenuItemHardware.setText("Hardware");
        jMenuItemHardware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHardwareActionPerformed(evt);
            }
        });
        jMenuProductsSetup.add(jMenuItemHardware);

        jMenuBar1.add(jMenuProductsSetup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneMaster)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneMaster)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Show Login Internal Frame 
        jInternalFrameLogin jframeLogin = new jInternalFrameLogin( this );
            jDesktopPaneMaster.add(jframeLogin);
            jframeLogin.setVisible(true);
        //  frameLogin.setLocation(400, 400);
            setInternalFrameLocationCentered(jframeLogin);
            
            
            
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        // Login Appears again
             // Show Login Internal Frame 
        jInternalFrameLogin jframeLogin = new jInternalFrameLogin( this );
            jDesktopPaneMaster.add(jframeLogin);
            jframeLogin.setVisible(true);
            setInternalFrameLocationCentered(jframeLogin);
        
            
        // disable all menus
          controlMenusAvaiblility(false);
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuItemExitApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitApplicationActionPerformed
            exitApplication();
    }//GEN-LAST:event_jMenuItemExitApplicationActionPerformed

    private void jMenuItemSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSoftwareActionPerformed
          jInternalFrameSoftware jFrameSoftware = new jInternalFrameSoftware(this);
            jDesktopPaneMaster.add(jFrameSoftware);
          jFrameSoftware.setVisible(true);
            setInternalFrameLocationCentered(jFrameSoftware);
    }//GEN-LAST:event_jMenuItemSoftwareActionPerformed

    private void jMenuItemHardwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHardwareActionPerformed
       jInternalFrameHardware jFrameHardware = new jInternalFrameHardware(this);
            jDesktopPaneMaster.add(jFrameHardware);
          jFrameHardware.setVisible(true);
            setInternalFrameLocationCentered(jFrameHardware);
    }//GEN-LAST:event_jMenuItemHardwareActionPerformed

    
     public void setInternalFrameLocationCentered(JInternalFrame jInternalFrame) {
       
        double desktopWidth = this.jDesktopPaneMaster.getSize().getWidth();
        double desktopHeight = this.jDesktopPaneMaster.getSize().getHeight();
        double jInternalFrameWidth = jInternalFrame.getSize().getWidth();
        double jInternalFrameHeight = jInternalFrame.getSize().getHeight();

        int x = (int) ((desktopWidth - jInternalFrameWidth) / 2);
        int y = (int) ((desktopHeight - jInternalFrameHeight) / 2);
        jInternalFrame.setLocation(x, y);
    }
     
     public void controlMenusAvaiblility(boolean action){
            jMenuProductsSetup.setEnabled(action);
            jMenuUserActions.setEnabled(action);
     }
     
      private void exitApplication() {
        int userOption = JOptionPane.showConfirmDialog(null, "Are you sure to Exit ? ", "Confirm Exit .. ", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (userOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneMaster;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemExitApplication;
    private javax.swing.JMenuItem jMenuItemHardware;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemSoftware;
    private javax.swing.JMenu jMenuProductsSetup;
    private javax.swing.JMenu jMenuUserActions;
    // End of variables declaration//GEN-END:variables

    public JDesktopPane getjDesktopPaneMaster() {
        return jDesktopPaneMaster;
    }

    public void setjDesktopPaneMaster(JDesktopPane jDesktopPaneMaster) {
        this.jDesktopPaneMaster = jDesktopPaneMaster;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenuItem getjMenuItemLogout() {
        return jMenuItemLogout;
    }

    public void setjMenuItemLogout(JMenuItem jMenuItemLogout) {
        this.jMenuItemLogout = jMenuItemLogout;
    }

    public JMenuItem getjMenuItemSoftware() {
        return jMenuItemSoftware;
    }

    public void setjMenuItemSoftware(JMenuItem jMenuItemSoftware) {
        this.jMenuItemSoftware = jMenuItemSoftware;
    }

    public JMenu getjMenuProductsSetup() {
        return jMenuProductsSetup;
    }

    public void setjMenuProductsSetup(JMenu jMenuProductsSetup) {
        this.jMenuProductsSetup = jMenuProductsSetup;
    }

    public JMenu getjMenuUserActions() {
        return jMenuUserActions;
    }

    public void setjMenuUserActions(JMenu jMenuUserActions) {
        this.jMenuUserActions = jMenuUserActions;
    }

  
   

}
