/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javase.oop.guiTest;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Administrator
 */
public class TestGUIComponents extends javax.swing.JFrame {

    /**
     * Creates new form TestGUIComponents
     */
    public TestGUIComponents() {
        initComponents();
         this.setLocationRelativeTo(null);
         // Set Radio buttons Action commands
         jRadioButtonRed.setActionCommand("Red");
         jRadioButtonBlue.setActionCommand("Blue");
         jRadioButtonYellow.setActionCommand("Yellow");
         
         jTextFieldCountrySelected.setText(jComboBoxCountries.getSelectedItem().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupColors = new javax.swing.ButtonGroup();
        jPanelWelcomeUser = new javax.swing.JPanel();
        jTextFieldUserName = new javax.swing.JTextField();
        jLabelUserName = new javax.swing.JLabel();
        jButtonWelcomeUser = new javax.swing.JButton();
        jPanelColors = new javax.swing.JPanel();
        jRadioButtonRed = new javax.swing.JRadioButton();
        jRadioButtonYellow = new javax.swing.JRadioButton();
        jRadioButtonBlue = new javax.swing.JRadioButton();
        jButtonColors = new javax.swing.JButton();
        jPanelSports = new javax.swing.JPanel();
        jCheckBoxFootball = new javax.swing.JCheckBox();
        jCheckBoxBasketball = new javax.swing.JCheckBox();
        jCheckBoxVolleyBall = new javax.swing.JCheckBox();
        jButtonSports = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSports = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxCountries = new javax.swing.JComboBox();
        jLabelCountries = new javax.swing.JLabel();
        jTextFieldCountrySelected = new javax.swing.JTextField();
        jButtonCountrySelected = new javax.swing.JButton();
        jLabelChoosenCountry = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListCourses = new javax.swing.JList();
        jButtonCourses = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaCourses = new javax.swing.JTextArea();
        jLabelPicture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelWelcomeUser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Welcome User", 0, 0, new java.awt.Font("Trajan Pro", 0, 12))); // NOI18N
        jPanelWelcomeUser.setOpaque(false);

        jLabelUserName.setText("User Name");

        jButtonWelcomeUser.setText("Welcome User");
        jButtonWelcomeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWelcomeUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelWelcomeUserLayout = new javax.swing.GroupLayout(jPanelWelcomeUser);
        jPanelWelcomeUser.setLayout(jPanelWelcomeUserLayout);
        jPanelWelcomeUserLayout.setHorizontalGroup(
            jPanelWelcomeUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWelcomeUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWelcomeUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonWelcomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanelWelcomeUserLayout.setVerticalGroup(
            jPanelWelcomeUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWelcomeUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelWelcomeUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUserName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonWelcomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanelColors.setBorder(javax.swing.BorderFactory.createTitledBorder("Colors"));
        jPanelColors.setOpaque(false);

        buttonGroupColors.add(jRadioButtonRed);
        jRadioButtonRed.setText("Red");
        jRadioButtonRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRedActionPerformed(evt);
            }
        });

        buttonGroupColors.add(jRadioButtonYellow);
        jRadioButtonYellow.setText("Yellow");
        jRadioButtonYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonYellowActionPerformed(evt);
            }
        });

        buttonGroupColors.add(jRadioButtonBlue);
        jRadioButtonBlue.setText("Blue");
        jRadioButtonBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBlueActionPerformed(evt);
            }
        });

        jButtonColors.setText("Read Colors");
        jButtonColors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColorsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelColorsLayout = new javax.swing.GroupLayout(jPanelColors);
        jPanelColors.setLayout(jPanelColorsLayout);
        jPanelColorsLayout.setHorizontalGroup(
            jPanelColorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColorsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelColorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelColorsLayout.createSequentialGroup()
                        .addComponent(jRadioButtonYellow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonColors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelColorsLayout.createSequentialGroup()
                        .addGroup(jPanelColorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonRed)
                            .addComponent(jRadioButtonBlue))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelColorsLayout.setVerticalGroup(
            jPanelColorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColorsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jRadioButtonRed)
                .addGap(5, 5, 5)
                .addGroup(jPanelColorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonColors, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonYellow))
                .addGap(5, 5, 5)
                .addComponent(jRadioButtonBlue)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanelSports.setBorder(javax.swing.BorderFactory.createTitledBorder("sports"));

        jCheckBoxFootball.setText("Football");
        jCheckBoxFootball.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxFootballItemStateChanged(evt);
            }
        });

        jCheckBoxBasketball.setText("Basket Ball");
        jCheckBoxBasketball.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxBasketballItemStateChanged(evt);
            }
        });

        jCheckBoxVolleyBall.setText("Volley Ball");
        jCheckBoxVolleyBall.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxVolleyBallItemStateChanged(evt);
            }
        });

        jButtonSports.setText("Read Sports");
        jButtonSports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSportsActionPerformed(evt);
            }
        });

        jTextAreaSports.setEditable(false);
        jTextAreaSports.setColumns(20);
        jTextAreaSports.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSports);

        javax.swing.GroupLayout jPanelSportsLayout = new javax.swing.GroupLayout(jPanelSports);
        jPanelSports.setLayout(jPanelSportsLayout);
        jPanelSportsLayout.setHorizontalGroup(
            jPanelSportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSportsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSports)
                    .addComponent(jCheckBoxFootball)
                    .addComponent(jCheckBoxBasketball)
                    .addComponent(jCheckBoxVolleyBall))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelSportsLayout.setVerticalGroup(
            jPanelSportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSportsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSportsLayout.createSequentialGroup()
                        .addComponent(jCheckBoxFootball)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxBasketball)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxVolleyBall)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSports))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose Country"));

        jComboBoxCountries.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Egypt", "USA", "France", "Saudi" }));
        jComboBoxCountries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCountriesActionPerformed(evt);
            }
        });

        jLabelCountries.setText("Countries");

        jButtonCountrySelected.setText("Selected Country");
        jButtonCountrySelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCountrySelectedActionPerformed(evt);
            }
        });

        jLabelChoosenCountry.setText("Country Selected");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCountries, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelChoosenCountry, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jTextFieldCountrySelected, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxCountries, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCountrySelected, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCountries, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCountries))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCountrySelected, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelChoosenCountry))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCountrySelected, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Courses"));

        jListCourses.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Java", "Oracle", "PHP", "Web design", "Python", "Ruby" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListCourses);

        jButtonCourses.setText("Show Selected Courses");
        jButtonCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCoursesActionPerformed(evt);
            }
        });

        jTextAreaCourses.setColumns(20);
        jTextAreaCourses.setRows(5);
        jScrollPane3.setViewportView(jTextAreaCourses);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonCourses))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCourses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabelPicture.setIcon(new javax.swing.ImageIcon("C:\\imgs\\java-duke-logo.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelSports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPicture)
                        .addGap(110, 110, 110))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelWelcomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanelWelcomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanelColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonWelcomeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWelcomeUserActionPerformed

     //  String userName =  jTextFieldUserName.getText();
         JOptionPane.showMessageDialog(null, "Welcome : "+jTextFieldUserName.getText(), "Welcome Message", JOptionPane.ERROR_MESSAGE );
    }//GEN-LAST:event_jButtonWelcomeUserActionPerformed

    private void jRadioButtonYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonYellowActionPerformed
         this.getContentPane().setBackground(Color.yellow);
    }//GEN-LAST:event_jRadioButtonYellowActionPerformed

    private void jRadioButtonBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBlueActionPerformed
         this.getContentPane().setBackground(Color.blue);
    }//GEN-LAST:event_jRadioButtonBlueActionPerformed

    private void jRadioButtonRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRedActionPerformed
       this.getContentPane().setBackground(Color.red);
    }//GEN-LAST:event_jRadioButtonRedActionPerformed

    private void jButtonColorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorsActionPerformed
          
       //  String redRadioChoosen = jRadioButtonRed.getActionCommand();
      //    JOptionPane.showMessageDialog(null, redRadioChoosen, "Color Choosen", JOptionPane.INFORMATION_MESSAGE);
          
               String radioChoosen = buttonGroupColors.getSelection().getActionCommand();
               JOptionPane.showMessageDialog(null, "Color Choosen : "+radioChoosen, "Choosen color", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonColorsActionPerformed

    private void jCheckBoxFootballItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxFootballItemStateChanged
          //  System.out.println("This is check box"); 
            setTextAreaSports();
    }//GEN-LAST:event_jCheckBoxFootballItemStateChanged

    private void jCheckBoxBasketballItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxBasketballItemStateChanged
        setTextAreaSports();
    }//GEN-LAST:event_jCheckBoxBasketballItemStateChanged

    private void jCheckBoxVolleyBallItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxVolleyBallItemStateChanged
      setTextAreaSports();
    }//GEN-LAST:event_jCheckBoxVolleyBallItemStateChanged

    private void jButtonSportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSportsActionPerformed
       setTextAreaSports();
    }//GEN-LAST:event_jButtonSportsActionPerformed

    private void jButtonCountrySelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCountrySelectedActionPerformed

           jTextFieldCountrySelected.setText(jComboBoxCountries.getSelectedItem().toString());
    }//GEN-LAST:event_jButtonCountrySelectedActionPerformed

    private void jComboBoxCountriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCountriesActionPerformed
        jTextFieldCountrySelected.setText(jComboBoxCountries.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBoxCountriesActionPerformed

    private void jButtonCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCoursesActionPerformed
            List coursesList = jListCourses.getSelectedValuesList();
            ArrayList<String> myList = (ArrayList) coursesList; 
        for(String item : myList){
                   System.out.println("item : "+item);
           }
    }//GEN-LAST:event_jButtonCoursesActionPerformed

    private void setTextAreaSports(){
         String sportsSelected =  
          "Football : "+ (jCheckBoxFootball.isSelected()?"Yes":"No")
          +"\nBasketball : "+(jCheckBoxBasketball.isSelected()?"Yes":"No")
          +"\nVolleyball : "+(jCheckBoxVolleyBall.isSelected()?"Yes":"No");
        
         jTextAreaSports.setText(sportsSelected);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestGUIComponents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestGUIComponents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestGUIComponents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestGUIComponents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestGUIComponents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupColors;
    private javax.swing.JButton jButtonColors;
    private javax.swing.JButton jButtonCountrySelected;
    private javax.swing.JButton jButtonCourses;
    private javax.swing.JButton jButtonSports;
    private javax.swing.JButton jButtonWelcomeUser;
    private javax.swing.JCheckBox jCheckBoxBasketball;
    private javax.swing.JCheckBox jCheckBoxFootball;
    private javax.swing.JCheckBox jCheckBoxVolleyBall;
    private javax.swing.JComboBox jComboBoxCountries;
    private javax.swing.JLabel jLabelChoosenCountry;
    private javax.swing.JLabel jLabelCountries;
    private javax.swing.JLabel jLabelPicture;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JList jListCourses;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelColors;
    private javax.swing.JPanel jPanelSports;
    private javax.swing.JPanel jPanelWelcomeUser;
    private javax.swing.JRadioButton jRadioButtonBlue;
    private javax.swing.JRadioButton jRadioButtonRed;
    private javax.swing.JRadioButton jRadioButtonYellow;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaCourses;
    private javax.swing.JTextArea jTextAreaSports;
    private javax.swing.JTextField jTextFieldCountrySelected;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
